/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TroubleshootingStep = IDL.Record({
  'description' : IDL.Text,
  'decisionPoint' : IDL.Opt(IDL.Text),
  'expectedOutcome' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Runbook = IDL.Record({
  'id' : IDL.Text,
  'issueName' : IDL.Text,
  'steps' : IDL.Vec(TroubleshootingStep),
  'symptoms' : IDL.Text,
});
export const Time = IDL.Int;
export const StepResult = IDL.Record({
  'step' : TroubleshootingStep,
  'timestamp' : Time,
  'outcome' : IDL.Text,
});
export const SessionStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'escalated' : IDL.Null,
  'inProgress' : IDL.Record({
    'results' : IDL.Vec(StepResult),
    'currentStep' : IDL.Nat,
  }),
});
export const TroubleshootingSession = IDL.Record({
  'id' : IDL.Text,
  'status' : SessionStatus,
  'issueDescription' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'updatedAt' : Time,
  'runbook' : Runbook,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeStep' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createRunbook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(TroubleshootingStep)],
      [],
      [],
    ),
  'escalate' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRunbook' : IDL.Func([IDL.Text], [Runbook], ['query']),
  'getSession' : IDL.Func([IDL.Text], [TroubleshootingSession], ['query']),
  'getSessionEscalationSummary' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listRunbooks' : IDL.Func([], [IDL.Vec(Runbook)], ['query']),
  'listUserSessions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TroubleshootingSession)],
      ['query'],
    ),
  'markResolved' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSessionsByStatus' : IDL.Func(
      [SessionStatus],
      [IDL.Vec(TroubleshootingSession)],
      ['query'],
    ),
  'startSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TroubleshootingStep = IDL.Record({
    'description' : IDL.Text,
    'decisionPoint' : IDL.Opt(IDL.Text),
    'expectedOutcome' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Runbook = IDL.Record({
    'id' : IDL.Text,
    'issueName' : IDL.Text,
    'steps' : IDL.Vec(TroubleshootingStep),
    'symptoms' : IDL.Text,
  });
  const Time = IDL.Int;
  const StepResult = IDL.Record({
    'step' : TroubleshootingStep,
    'timestamp' : Time,
    'outcome' : IDL.Text,
  });
  const SessionStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'escalated' : IDL.Null,
    'inProgress' : IDL.Record({
      'results' : IDL.Vec(StepResult),
      'currentStep' : IDL.Nat,
    }),
  });
  const TroubleshootingSession = IDL.Record({
    'id' : IDL.Text,
    'status' : SessionStatus,
    'issueDescription' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'updatedAt' : Time,
    'runbook' : Runbook,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeStep' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createRunbook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(TroubleshootingStep)],
        [],
        [],
      ),
    'escalate' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRunbook' : IDL.Func([IDL.Text], [Runbook], ['query']),
    'getSession' : IDL.Func([IDL.Text], [TroubleshootingSession], ['query']),
    'getSessionEscalationSummary' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listRunbooks' : IDL.Func([], [IDL.Vec(Runbook)], ['query']),
    'listUserSessions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TroubleshootingSession)],
        ['query'],
      ),
    'markResolved' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSessionsByStatus' : IDL.Func(
        [SessionStatus],
        [IDL.Vec(TroubleshootingSession)],
        ['query'],
      ),
    'startSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };