/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Runbook {
  'id' : string,
  'issueName' : string,
  'steps' : Array<TroubleshootingStep>,
  'symptoms' : string,
}
export type SessionStatus = { 'resolved' : null } |
  { 'escalated' : null } |
  { 'inProgress' : { 'results' : Array<StepResult>, 'currentStep' : bigint } };
export interface StepResult {
  'step' : TroubleshootingStep,
  'timestamp' : Time,
  'outcome' : string,
}
export type Time = bigint;
export interface TroubleshootingSession {
  'id' : string,
  'status' : SessionStatus,
  'issueDescription' : string,
  'createdAt' : Time,
  'user' : Principal,
  'updatedAt' : Time,
  'runbook' : Runbook,
}
export interface TroubleshootingStep {
  'description' : string,
  'decisionPoint' : [] | [string],
  'expectedOutcome' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeStep' : ActorMethod<[string, string], undefined>,
  'createRunbook' : ActorMethod<
    [string, string, string, Array<TroubleshootingStep>],
    undefined
  >,
  'escalate' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRunbook' : ActorMethod<[string], Runbook>,
  'getSession' : ActorMethod<[string], TroubleshootingSession>,
  'getSessionEscalationSummary' : ActorMethod<[string], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listRunbooks' : ActorMethod<[], Array<Runbook>>,
  'listUserSessions' : ActorMethod<[Principal], Array<TroubleshootingSession>>,
  'markResolved' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchSessionsByStatus' : ActorMethod<
    [SessionStatus],
    Array<TroubleshootingSession>
  >,
  'startSession' : ActorMethod<[string, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];