/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface TroubleshootingSession {
    id: string;
    status: SessionStatus;
    issueDescription: string;
    createdAt: Time;
    user: Principal;
    updatedAt: Time;
    runbook: Runbook;
}
export type SessionStatus = {
    __kind__: "resolved";
    resolved: null;
} | {
    __kind__: "escalated";
    escalated: null;
} | {
    __kind__: "inProgress";
    inProgress: {
        results: Array<StepResult>;
        currentStep: bigint;
    };
};
export interface StepResult {
    step: TroubleshootingStep;
    timestamp: Time;
    outcome: string;
}
export interface TroubleshootingStep {
    description: string;
    decisionPoint?: string;
    expectedOutcome: string;
}
export interface UserProfile {
    name: string;
}
export interface Runbook {
    id: string;
    issueName: string;
    steps: Array<TroubleshootingStep>;
    symptoms: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeStep(sessionId: string, outcome: string): Promise<void>;
    createRunbook(id: string, issueName: string, symptoms: string, steps: Array<TroubleshootingStep>): Promise<void>;
    escalate(sessionId: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getRunbook(id: string): Promise<Runbook>;
    getSession(sessionId: string): Promise<TroubleshootingSession>;
    getSessionEscalationSummary(sessionId: string): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listRunbooks(): Promise<Array<Runbook>>;
    listUserSessions(user: Principal): Promise<Array<TroubleshootingSession>>;
    markResolved(sessionId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchSessionsByStatus(status: SessionStatus): Promise<Array<TroubleshootingSession>>;
    startSession(issueDescription: string, runbookId: string): Promise<string>;
}
import type { Runbook as _Runbook, SessionStatus as _SessionStatus, StepResult as _StepResult, Time as _Time, TroubleshootingSession as _TroubleshootingSession, TroubleshootingStep as _TroubleshootingStep, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeStep(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeStep(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeStep(arg0, arg1);
            return result;
        }
    }
    async createRunbook(arg0: string, arg1: string, arg2: string, arg3: Array<TroubleshootingStep>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createRunbook(arg0, arg1, arg2, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRunbook(arg0, arg1, arg2, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async escalate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.escalate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.escalate(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRunbook(arg0: string): Promise<Runbook> {
        if (this.processError) {
            try {
                const result = await this.actor.getRunbook(arg0);
                return from_candid_Runbook_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRunbook(arg0);
            return from_candid_Runbook_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: string): Promise<TroubleshootingSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_TroubleshootingSession_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_TroubleshootingSession_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionEscalationSummary(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionEscalationSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionEscalationSummary(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listRunbooks(): Promise<Array<Runbook>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRunbooks();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRunbooks();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUserSessions(arg0: Principal): Promise<Array<TroubleshootingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserSessions(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserSessions(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async markResolved(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markResolved(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markResolved(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchSessionsByStatus(arg0: SessionStatus): Promise<Array<TroubleshootingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSessionsByStatus(to_candid_SessionStatus_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSessionsByStatus(to_candid_SessionStatus_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async startSession(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.startSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSession(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Runbook_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Runbook): Runbook {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_StepResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StepResult): StepResult {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_TroubleshootingSession_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TroubleshootingSession): TroubleshootingSession {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TroubleshootingStep_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TroubleshootingStep): TroubleshootingStep {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    issueName: string;
    steps: Array<_TroubleshootingStep>;
    symptoms: string;
}): {
    id: string;
    issueName: string;
    steps: Array<TroubleshootingStep>;
    symptoms: string;
} {
    return {
        id: value.id,
        issueName: value.issueName,
        steps: from_candid_vec_n11(_uploadFile, _downloadFile, value.steps),
        symptoms: value.symptoms
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    decisionPoint: [] | [string];
    expectedOutcome: string;
}): {
    description: string;
    decisionPoint?: string;
    expectedOutcome: string;
} {
    return {
        description: value.description,
        decisionPoint: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.decisionPoint)),
        expectedOutcome: value.expectedOutcome
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _SessionStatus;
    issueDescription: string;
    createdAt: _Time;
    user: Principal;
    updatedAt: _Time;
    runbook: _Runbook;
}): {
    id: string;
    status: SessionStatus;
    issueDescription: string;
    createdAt: Time;
    user: Principal;
    updatedAt: Time;
    runbook: Runbook;
} {
    return {
        id: value.id,
        status: from_candid_SessionStatus_n17(_uploadFile, _downloadFile, value.status),
        issueDescription: value.issueDescription,
        createdAt: value.createdAt,
        user: value.user,
        updatedAt: value.updatedAt,
        runbook: from_candid_Runbook_n9(_uploadFile, _downloadFile, value.runbook)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    results: Array<_StepResult>;
    currentStep: bigint;
}): {
    results: Array<StepResult>;
    currentStep: bigint;
} {
    return {
        results: from_candid_vec_n20(_uploadFile, _downloadFile, value.results),
        currentStep: value.currentStep
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    step: _TroubleshootingStep;
    timestamp: _Time;
    outcome: string;
}): {
    step: TroubleshootingStep;
    timestamp: Time;
    outcome: string;
} {
    return {
        step: from_candid_TroubleshootingStep_n12(_uploadFile, _downloadFile, value.step),
        timestamp: value.timestamp,
        outcome: value.outcome
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    escalated: null;
} | {
    inProgress: {
        results: Array<_StepResult>;
        currentStep: bigint;
    };
}): {
    __kind__: "resolved";
    resolved: null;
} | {
    __kind__: "escalated";
    escalated: null;
} | {
    __kind__: "inProgress";
    inProgress: {
        results: Array<StepResult>;
        currentStep: bigint;
    };
} {
    return "resolved" in value ? {
        __kind__: "resolved",
        resolved: value.resolved
    } : "escalated" in value ? {
        __kind__: "escalated",
        escalated: value.escalated
    } : "inProgress" in value ? {
        __kind__: "inProgress",
        inProgress: from_candid_record_n19(_uploadFile, _downloadFile, value.inProgress)
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TroubleshootingStep>): Array<TroubleshootingStep> {
    return value.map((x)=>from_candid_TroubleshootingStep_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StepResult>): Array<StepResult> {
    return value.map((x)=>from_candid_StepResult_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Runbook>): Array<Runbook> {
    return value.map((x)=>from_candid_Runbook_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TroubleshootingSession>): Array<TroubleshootingSession> {
    return value.map((x)=>from_candid_TroubleshootingSession_n15(_uploadFile, _downloadFile, x));
}
function to_candid_SessionStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionStatus): _SessionStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_StepResult_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StepResult): _StepResult {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_TroubleshootingStep_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TroubleshootingStep): _TroubleshootingStep {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    results: Array<StepResult>;
    currentStep: bigint;
}): {
    results: Array<_StepResult>;
    currentStep: bigint;
} {
    return {
        results: to_candid_vec_n28(_uploadFile, _downloadFile, value.results),
        currentStep: value.currentStep
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    step: TroubleshootingStep;
    timestamp: Time;
    outcome: string;
}): {
    step: _TroubleshootingStep;
    timestamp: _Time;
    outcome: string;
} {
    return {
        step: to_candid_TroubleshootingStep_n4(_uploadFile, _downloadFile, value.step),
        timestamp: value.timestamp,
        outcome: value.outcome
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    decisionPoint?: string;
    expectedOutcome: string;
}): {
    description: string;
    decisionPoint: [] | [string];
    expectedOutcome: string;
} {
    return {
        description: value.description,
        decisionPoint: value.decisionPoint ? candid_some(value.decisionPoint) : candid_none(),
        expectedOutcome: value.expectedOutcome
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "resolved";
    resolved: null;
} | {
    __kind__: "escalated";
    escalated: null;
} | {
    __kind__: "inProgress";
    inProgress: {
        results: Array<StepResult>;
        currentStep: bigint;
    };
}): {
    resolved: null;
} | {
    escalated: null;
} | {
    inProgress: {
        results: Array<_StepResult>;
        currentStep: bigint;
    };
} {
    return value.__kind__ === "resolved" ? {
        resolved: value.resolved
    } : value.__kind__ === "escalated" ? {
        escalated: value.escalated
    } : value.__kind__ === "inProgress" ? {
        inProgress: to_candid_record_n27(_uploadFile, _downloadFile, value.inProgress)
    } : value;
}
function to_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<StepResult>): Array<_StepResult> {
    return value.map((x)=>to_candid_StepResult_n29(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TroubleshootingStep>): Array<_TroubleshootingStep> {
    return value.map((x)=>to_candid_TroubleshootingStep_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
